'''
In this file you can define the branch to be included in the flat ntuple.
You can find some basic quantities here, expand with more specific observables,
such as isolation etc...
'''
branches = [
    'run'  ,
    'lumi' ,
    'event',
    'nvtx' ,

    'tau_reco_chargedIso'               ,
    'tau_reco_dxy'                      ,
    'tau_reco_dz'                       ,
    'tau_reco_eta'                      ,
    'tau_reco_leadTkDeltaEta'           ,
    'tau_reco_leadTkDeltaPhi'           ,
    'tau_reco_leadTkPtOverTauPt'        ,
    'tau_reco_mass'                     ,
    'tau_reco_neutralIso'               ,
    'tau_reco_phi'                      ,
    'tau_reco_photonsOutsideSignalCone' ,
    'tau_reco_pt'                       ,
    'tau_reco_puCorr'                   ,
    'tau_reco_rawAntiEle'               ,
    'tau_reco_rawIso'                   ,
    'tau_reco_rawIsodR03'               ,
    'tau_reco_rawMVAnewDM2017v2'        ,
    'tau_reco_rawMVAoldDM'              ,
    'tau_reco_rawMVAoldDM2017v1'        ,
    'tau_reco_rawMVAoldDM2017v2'        ,
    'tau_reco_rawMVAoldDMdR032017v2'    ,
    'tau_reco_charge'                   ,
    'tau_reco_decayMode'                ,
    'tau_reco_jetIdx'                   ,
    'tau_reco_rawAntiEleCat'            ,
    'tau_reco_idAntiEle'                ,
    'tau_reco_idAntiMu'                 ,
    'tau_reco_idDecayMode'              ,
    'tau_reco_idDecayModeNewDMs'        ,
    'tau_reco_idMVAnewDM2017v2'         ,
    'tau_reco_idMVAoldDM'               ,
    'tau_reco_idMVAoldDM2017v1'         ,
    'tau_reco_idMVAoldDM2017v2'         ,
    'tau_reco_idMVAoldDMdR032017v2'     ,
    'tau_reco_genPartIdx'               ,
    'tau_reco_genPartFlav'              ,
    
    'gen_vis_tau_eta'                   ,
    'gen_vis_tau_mass'                  ,
    'gen_vis_tau_phi'                   ,
    'gen_vis_tau_pt'                    ,
    'gen_vis_tau_charge'                ,
    'gen_vis_tau_genPartIdxMother'      ,
    'gen_vis_tau_status'                ,

]